### ISSUE TITLE
Wildcard support in AddIPAddressResourceRecord

### ISSUE THREAD

**Issue by Rottweiler** [kapetan/dns#4]
Hi. I love this project, it's exactly what I was looking for. Only one thing is missing though, and that is wildcard support when adding new records. This feature would allow me to complete my own project.

Please do consider adding it!

Sincerely, Rottweiler.

**Comment by kapetan** [comment]
Hi. Just so that I understand the issue correctly. The problem is that adding a record like `AddIPAddressResourceRecord("*.google.com", "127.0.0.1")` is not intercepted by the server when requesting `me.google.com`?

It should be easy enough to fix, but I don't have my development machine right now, so it may take some time.

**Comment by Rottweiler** [comment]
Exactly, and okay.

**Comment by kapetan** [comment]
I've published v1.2.0 with wildcard support.
